"""empty message

Revision ID: 446c4aab8a1c
Revises: 
Create Date: 2025-11-05 21:01:53.372663

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '446c4aab8a1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户id'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='标题'),
    sa.Column('is_default', sa.Integer(), nullable=True, comment='是否默认'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('username', sa.String(length=32), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=64), nullable=True, comment='密码'),
    sa.Column('nickname', sa.String(length=32), nullable=True, comment='昵称'),
    sa.Column('avatar_url', sa.String(length=64), nullable=True, comment='头像地址'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态(0:停用,1:待审核,2:正常,3:已注销)'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='ix_sys_user_username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('conversations')
    # ### end Alembic commands ###
