"""empty message

Revision ID: 063e0eeab6e9
Revises: 446c4aab8a1c
Create Date: 2025-11-08 17:34:46.306419

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '063e0eeab6e9'
down_revision = '446c4aab8a1c'
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID'),
    sa.Column('file_uuid', sa.String(length=36), nullable=False, comment='文件标识符'),
    sa.Column('storage_driver', sa.String(length=20), nullable=False, comment='存储类型(local, s3)'),
    sa.Column('storage_path', sa.String(length=255), nullable=False, comment='文件路径'),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('storage_name', sa.String(length=255), nullable=False, comment='存储文件名'),
    sa.Column('file_hash', sa.String(length=64), nullable=False, comment='文件哈希值(SHA-256)'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小(字节)'),
    sa.Column('file_extension', sa.String(length=20), nullable=True, comment='文件扩展名 (例如: jpg, pdf)'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'),
    sa.Column('conversation_id', sa.Integer(), nullable=True, comment='对话ID'),
    sa.Column('state', sa.Integer(), nullable=True, comment='状态(0: 初始化, 1: 完成)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='软删除时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('conversations', sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'))
    op.drop_column('conversations', 'create_at')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'))
    op.drop_column('users', 'create_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_at', mysql.DATETIME(), nullable=True, comment='创建时间'))
    op.drop_column('users', 'created_at')
    op.add_column('conversations', sa.Column('create_at', mysql.DATETIME(), nullable=True, comment='创建时间'))
    op.drop_column('conversations', 'created_at')
    op.drop_table('files')
    # ### end Alembic commands ###
